<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="19.685" tests="12" failures="7">
  <testsuite name="Root Suite" timestamp="2020-01-25T17:57:48" tests="0" failures="1" time="0">
    <testcase name=" Uncaught error outside test suite" time="0" classname="Uncaught error outside test suite">
      <failure message="listen EADDRINUSE: address already in use 0.0.0.0:8000" type="Error"><![CDATA[Error: listen EADDRINUSE: address already in use 0.0.0.0:8000
    at Server.setupListenHandle [as _listen2] (net.js:1279:14)
    at listenInCluster (net.js:1327:12)
    at doListen (net.js:1460:7)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)]]></failure>
    </testcase>
  </testsuite>
  <testsuite name="Weather app 
" timestamp="2020-01-25T17:57:48" tests="12" file="/home/wuwei/Documentos/JULIETH/weather-finder/test/test.js" failures="6" time="19.685">
    <testcase name="Weather app 
 should suggest items on typing city name" time="1.508" classname="should suggest items on typing city name">
      <failure message="javascript error: Cannot read property &apos;innerText&apos; of undefined
  (Session info: headless chrome=79.0.3945.88)
  (Driver info: chromedriver=78.0.3904.70 (edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}),platform=Linux 4.15.0-34-generic x86_64)" type="JavascriptError"><![CDATA[JavascriptError: javascript error: Cannot read property 'innerText' of undefined
  (Session info: headless chrome=79.0.3945.88)
  (Driver info: chromedriver=78.0.3904.70 (edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}),platform=Linux 4.15.0-34-generic x86_64)
    at Object.checkLegacyResponse (node_modules/selenium-webdriver/lib/error.js:546:15)
    at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (node_modules/selenium-webdriver/lib/http.js:441:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
From: Task: WebDriver.executeScript()
    at thenableWebDriverProxy.schedule (node_modules/selenium-webdriver/lib/webdriver.js:807:17)
    at thenableWebDriverProxy.executeScript (node_modules/selenium-webdriver/lib/webdriver.js:878:16)
    at Context.<anonymous> (test/test.js:65:38)
    at process._tickCallback (internal/process/next_tick.js:68:7)]]></failure>
    </testcase>
    <testcase name="Weather app 
 selecting a suggestion should change the input field value to the selected city&apos;s name" time="1.369" classname="selecting a suggestion should change the input field value to the selected city&apos;s name">
      <failure message="expected &apos;dall&apos; to equal &apos;Dallas&apos;" type="AssertionError"><![CDATA[AssertionError: expected 'dall' to equal 'Dallas'
    at Context.<anonymous> (test/test.js:88:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)]]></failure>
    </testcase>
    <testcase name="Weather app 
 should add the contents to the selected section on selecting an option" time="1.329" classname="should add the contents to the selected section on selecting an option">
      <failure message="expected &apos;&apos; to equal &apos;Dallas&apos;" type="AssertionError"><![CDATA[AssertionError: expected '' to equal 'Dallas'
    at Context.<anonymous> (test/test.js:107:32)
    at process._tickCallback (internal/process/next_tick.js:68:7)]]></failure>
    </testcase>
    <testcase name="Weather app 
 should debounce before making API calls - no result found" time="5.094" classname="should debounce before making API calls - no result found">
    </testcase>
    <testcase name="Weather app 
 should debounce before making API calls - result should have final call results" time="1.093" classname="should debounce before making API calls - result should have final call results">
      <failure message="expected &apos;No Info available!&apos; to equal &apos;No results&apos;" type="AssertionError"><![CDATA[AssertionError: expected 'No Info available!' to equal 'No results'
    at Context.<anonymous> (test/test.js:135:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)]]></failure>
    </testcase>
    <testcase name="Weather app 
 should show &quot;No results&quot; message if the data is empty" time="1.318" classname="should show &quot;No results&quot; message if the data is empty">
      <failure message="expected &apos;No Info available!&apos; to equal &apos;No results&apos;" type="AssertionError"><![CDATA[AssertionError: expected 'No Info available!' to equal 'No results'
    at Context.<anonymous> (test/test.js:174:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)]]></failure>
    </testcase>
    <testcase name="Weather app 
 should show &quot;No results&quot; message in red color" time="1.32" classname="should show &quot;No results&quot; message in red color">
      <failure message="expected false to be true" type="AssertionError"><![CDATA[AssertionError: expected false to be true
    at Context.<anonymous> (test/test.js:192:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)]]></failure>
    </testcase>
    <testcase name="Weather app 
 should have a reset button which resets all entries" time="1.384" classname="should have a reset button which resets all entries">
    </testcase>
    <testcase name="Weather app 
 make sure api is hit - test 1" time="1.328" classname="make sure api is hit - test 1">
    </testcase>
    <testcase name="Weather app 
 make sure api is hit - test 2" time="1.298" classname="make sure api is hit - test 2">
    </testcase>
    <testcase name="Weather app 
 make sure api is hit - test 3" time="1.299" classname="make sure api is hit - test 3">
    </testcase>
    <testcase name="Weather app 
 make sure api is hit - test 4" time="1.345" classname="make sure api is hit - test 4">
    </testcase>
  </testsuite>
</testsuites>